---
title: "Publications"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Bode, S., **Jiwa, M.**, Chum, C., Frost, L., Heekeren, H. R., Wingenfeld, K., & Deuter, C. E. (2023). Non-instrumental information seeking is resistant to acute stress. *Scientific Reports*, 13(1), 19505.

**Jiwa, M.,** Cooper, P. S., Chong, T. T. J., & Bode, S. (2023). Hedonism as a motive for information search: biased information-seeking leads to biased beliefs. *Scientific Reports*, 13(1), 2086. https://doi.org/10.1038/s41598-023-29429-8

Bode S., Sun X., **Jiwa M.**, Cooper P. S., Chong T. T. J., & Egorova-Brumley N. (2023) When knowledge hurts: humans are willing to receive pain for obtaining non-instrumental information. *Proc. R. Soc. B* 290: 20231175. https://doi.org/10.1098/rspb.2023.1175

**Jiwa, M.**, Cooper, P. S., Chong, T. T. J., & Bode, S. (2021). Choosing increases the value of non-instrumental information. *Scientific Reports*, 11(1), 1-11. https://doi.org/10.1038/s41598-021-88031-y

Feuerriegel, D., **Jiwa, M.**, Turner, W. F., Andrejević, M., Hester, R., & Bode, S. (2021). Tracking dynamic adjustments to decision making and performance monitoring processes in conflict tasks. *NeuroImage*, 238, 118265. https://doi.org/10.1016/j.neuroimage.2021.118265

**Jiwa, M. W.**, & Jiwa, M. (2020). Why the effectiveness of a face mask is not limited to its infection control. *The Journal of Health Design*, 5(3). https://doi.org/10.21853/JHD.2020.117

# Conference Presentations & Workshops

**Jiwa, M.,** Rothkopf, C., & Gottlieb, J. (2024). Generating Saccades to Reduce Uncertainty: Cognitive and Sensorimotor Trade-Offs. Vision Science Society Conference, St. Pete Beach, Florida, USA 

**Jiwa, M.,** Cooper, P. S., Chong, T. T. J., & Bode, S. (2022). Hedonism in Information Search – Biased
Information-Seeking Leads to Biased Beliefs. Australasian Cognitive Neuroscience Society Conference,
The University of Queensland, Australia.

**Jiwa, M.,** Cooper, P. S., Chong, T. T. J., & Bode, S. (2022). Hedonism in Information Search – Biased Information-Seeking Leads to Biased Beliefs. Society for Mathematical Psychology Virtual Conference, Toronto.

**Jiwa, M.** (2022) Workflow in R: How to Structure a Research Project. Graduate Researchers in Psychological Sciences Annual Workshops, The University of Melbourne, Australia.

**Jiwa, M.,** Cooper, P. S., Chong, T. T. J., & Bode, S. (2021). Choosing Increases the Value of Non-Instrumental Information. Australasian Cognitive Neuroscience Society Conference, The University of Melbourne, Australia.

**Jiwa, M.,** Cooper, P. S., Chong, T. T. J., & Bode, S. (2021). Choosing Increases the Value of Non-Instrumental Information. EPS Decision Making in Voluntary Action Workshop, University College London, UK.

**Jiwa, M.,** Cooper, P. S., Chong, T. T. J., & Bode, S. (2020). Choosing to Know: Agency Increases the Value of Non-Instrumental Information. MDHS Graduate Research Conference, The University of Melbourne, Australia.



